export type DataTaxonomyItem = {
  id: number;
  item: string;
  category: string;
};

// Appendix A — Data taxonomy (55 items, original order)
export const dataTaxonomy: DataTaxonomyItem[] = [
  { id: 1, item: "RGB", category: "Vision / Optical" },
  { id: 2, item: "RGB-D", category: "Vision / Optical" },
  { id: 3, item: "LiDAR", category: "Depth / Ranging" },
  { id: 4, item: "RF", category: "RF / Wireless" },
  { id: 5, item: "Thermal", category: "Vision / Optical" },
  { id: 6, item: "mmWave", category: "RF / Wireless" },
  { id: 7, item: "WiFi-CSI", category: "RF / Wireless" },
  { id: 8, item: "IMU", category: "Motion / Inertial" },
  { id: 9, item: "Tele-op", category: "Capture method" },
  { id: 10, item: "Joint position", category: "Motion / Inertial" },
  { id: 11, item: "Dash cam", category: "Capture method" },
  { id: 12, item: "Texture / cloth data", category: "Material" },
  { id: 13, item: "CAD / .obj", category: "Geometry / 3D" },
  { id: 14, item: "3D", category: "Geometry / 3D" },
  { id: 15, item: "UGC", category: "Source / Content" },
  { id: 16, item: "Sound / audio", category: "Acoustic" },
  { id: 17, item: "Satellite data", category: "Capture method" },
  { id: 18, item: "Sonar", category: "Depth / Ranging" },
  { id: 19, item: "Molecular", category: "Medical / Bio" },
  { id: 20, item: "Tactile", category: "Contact / Force" },
  { id: 21, item: "Force tile data", category: "Contact / Force" },
  { id: 22, item: "4D", category: "Geometry / 3D" },
  { id: 23, item: "Ultra-wideband (UWB)", category: "Depth / Ranging" },
  { id: 24, item: "MRI", category: "Medical / Bio" },
  { id: 25, item: "CT", category: "Medical / Bio" },
  { id: 26, item: "Orthopedic data", category: "Medical / Bio" },
  { id: 27, item: "CNC data", category: "Capture method" },
  { id: 28, item: "Friction data", category: "Contact / Force" },
  { id: 29, item: "Telescopic data", category: "Vision / Optical" },
  { id: 30, item: "Photon reader", category: "Vision / Optical" },
  { id: 31, item: "Pop sim", category: "Synthetic / Derived" },
  { id: 32, item: "Multi-modal", category: "Synthetic / Derived" },
  { id: 33, item: "Olfactory data", category: "Environmental" },
  { id: 34, item: "Weather", category: "Environmental" },
  { id: 35, item: "Physics data", category: "Synthetic / Derived" },
  { id: 36, item: "Visual", category: "Vision / Optical" },
  { id: 37, item: "Temperature", category: "Environmental" },
  { id: 38, item: "Vertical", category: "Other" },
  { id: 39, item: "360° panorama", category: "Capture method" },
  { id: 40, item: "Egocentric video", category: "Capture method" },
  { id: 41, item: "Multi-view rig", category: "Capture method" },
  { id: 42, item: "Photogrammetry", category: "Capture method" },
  { id: 43, item: "Motion capture", category: "Capture method" },
  { id: 44, item: "Aerial / Drone", category: "Capture method" },
  { id: 45, item: "Event camera", category: "Vision / Optical" },
  { id: 46, item: "Hyperspectral", category: "Vision / Optical" },
  { id: 47, item: "Radar", category: "Depth / Ranging" },
  { id: 48, item: "Structured light", category: "Depth / Ranging" },
  { id: 49, item: "GPS / GNSS", category: "Motion / Inertial" },
  { id: 50, item: "Wheel odometry", category: "Motion / Inertial" },
  { id: 51, item: "Force / torque", category: "Contact / Force" },
  { id: 52, item: "Point cloud", category: "Geometry / 3D" },
  { id: 53, item: "Medical imaging", category: "Medical / Bio" },
  { id: 54, item: "Simulation / Synthetic", category: "Synthetic / Derived" },
  { id: 55, item: "Unknown / not sure yet", category: "Unknown" },
];
